apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-foo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-foo-app
  template:
    metadata:
      labels:
        app: kube-foo-app
    spec:
      containers:
        - name: kube-foo-app
          image: silverfang94/app_foo:v1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 3001
            protocol: TCP