apiVersion: v1
kind: Service
metadata:
  name: kube-foo-svc
spec:
  # type: NodePort
  selector:
    app: kube-foo-app
  ports:
    - port: 8080
      targetPort: 3001
      # nodePort: 32001
      protocol: TCP